CREATE DATABASE IF NOT EXISTS VACCINATION_SYSTEM;
USE VACCINATION_SYSTEM;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BILL;
DROP TABLE IF EXISTS VACCINATION_FORM_DETAIL;
DROP TABLE IF EXISTS VACCINATION_FORM;
DROP TABLE IF EXISTS VACCINE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS DOCTOR;
DROP TABLE IF EXISTS CASHIER;
DROP TABLE IF EXISTS INVENTORY_MANAGER;
DROP TABLE IF EXISTS ADMINISTRATOR;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS VACCINE_TYPE;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE VACCINE_TYPE (
    VACCINE_TYPE_ID CHAR(10) PRIMARY KEY,
    VACCINE_TYPE VARCHAR(50)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID CHAR(10) PRIMARY KEY,
    AUTHORITY VARCHAR(50),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100),
    EMAIL VARCHAR(100)
);

CREATE TABLE INVENTORY_MANAGER (
    INVENTORY_MANAGER_ID CHAR(10) PRIMARY KEY,
    ACCOUNT_ID CHAR(10) UNIQUE,
    NAME VARCHAR(100),
    ROLE VARCHAR(50),
    DATE_OF_BIRTH DATE,
    PHONE_NUM CHAR(15),
    ADDRESS VARCHAR(200),
    CONSTRAINT FK_IM_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE ADMINISTRATOR (
    ADMINISTRATOR_ID CHAR(10) PRIMARY KEY,
    ACCOUNT_ID CHAR(10) UNIQUE,
    ROLE VARCHAR(50),
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    PHONE_NUM CHAR(15),
    ADDRESS VARCHAR(200),
    CONSTRAINT FK_ADMIN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE DOCTOR (
    DOCTOR_ID CHAR(10) PRIMARY KEY,
    ACCOUNT_ID CHAR(10) UNIQUE,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ROLE VARCHAR(50),
    PHONE_NUM CHAR(15),
    ADDRESS VARCHAR(200),
    SPECIALIST VARCHAR(100),
    CERTIFICATE VARCHAR(100),
    CONSTRAINT FK_DOCTOR_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE CASHIER (
    CASHIER_ID CHAR(10) PRIMARY KEY,
    ACCOUNT_ID CHAR(10) UNIQUE,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    PHONE_NUM CHAR(15),
    ADDRESS VARCHAR(200),
    ROLE VARCHAR(50),
    CONSTRAINT FK_CASHIER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID CHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(20),
    BIOGRAPHY VARCHAR(500),
    PHONE_NUM CHAR(15),
    EMAIL VARCHAR(100)
);

CREATE TABLE VACCINE (
    VACCINE_ID CHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    PRODUCTION_DATE DATE,
    EXPIRY DATE,
    VACCINE_LOT CHAR(20),
    QUANTITY_AVAILABLE INT,
    PRICE FLOAT,
    VACCINE_TYPE_ID CHAR(10),
    INVENTORY_MANAGER_ID CHAR(10),
    CONSTRAINT FK_VACCINE_TYPE FOREIGN KEY (VACCINE_TYPE_ID)
        REFERENCES VACCINE_TYPE(VACCINE_TYPE_ID),
    CONSTRAINT FK_VACCINE_IM FOREIGN KEY (INVENTORY_MANAGER_ID)
        REFERENCES INVENTORY_MANAGER(INVENTORY_MANAGER_ID)
);

CREATE TABLE VACCINATION_FORM (
    VACCINATION_FORM_ID CHAR(10) PRIMARY KEY,
    CUSTOMER_ID CHAR(10),
    DOCTOR_ID CHAR(10),
    CASHIER_ID CHAR(10),
    VACCINATION_DATE DATE,
    CONSTRAINT FK_VF_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_VF_DOCTOR FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTOR(DOCTOR_ID),
    CONSTRAINT FK_VF_CASHIER FOREIGN KEY (CASHIER_ID)
        REFERENCES CASHIER(CASHIER_ID)
);

CREATE TABLE VACCINATION_FORM_DETAIL (
    VACCINATION_FORM_ID CHAR(10),
    VACCINE_ID CHAR(10),
    `CNT` INT,
    DOSE INT,
    RETENTION DATE,
    PRICE FLOAT,
    CONSTRAINT PK_VFD PRIMARY KEY (VACCINATION_FORM_ID, VACCINE_ID),
    CONSTRAINT FK_VFD_FORM FOREIGN KEY (VACCINATION_FORM_ID)
        REFERENCES VACCINATION_FORM(VACCINATION_FORM_ID),
    CONSTRAINT FK_VFD_VACCINE FOREIGN KEY (VACCINE_ID)
        REFERENCES VACCINE(VACCINE_ID)
);

CREATE TABLE BILL (
    BILL_ID CHAR(10) PRIMARY KEY,
    DISCOUNT FLOAT,
    DUE_DATE DATE,
    TOTAL_AMOUNT FLOAT,
    CASHIER_ID CHAR(10),
    VACCINATION_FORM_ID CHAR(10) UNIQUE,
    CONSTRAINT FK_BILL_CASHIER FOREIGN KEY (CASHIER_ID)
        REFERENCES CASHIER(CASHIER_ID),
    CONSTRAINT FK_BILL_FORM FOREIGN KEY (VACCINATION_FORM_ID)
        REFERENCES VACCINATION_FORM(VACCINATION_FORM_ID)
);